fsk_modem:
  bit_rate: 4.8 #Kbps
  sampling_rate: 196 #Ksps
  freq_dev: 4.5 #KHz  
  num_bits: 10000
  awgn_enable: True 
  snr: 9 #dB

usrp:
  band: n78
  center_freq: 400 #MHxz
  sampling_rate: 196 #KSPS
