fsk_modem:
  bit_rate: 19.2 #Kbps
  sampling_rate: 192 #Ksps
  freq_dev: 4.3 #KHz  
  num_bits: 10240
  awgn_en: False 
  chfir_en: True 
  snr: 9 #dB
  padding_len: 4 
  loopBack_en: True
usrp:
  band: n78
  center_freq: 435 #MHxz
  sampling_rate: 192 #KSPS
  rx_duration_sec: 2 # sec  
