fsk_modem:
  bit_rate: 19.2 #Kbps
  sampling_rate: 196 #Ksps
  freq_dev: 4.3 #KHz  
  num_bits: 128
  awgn_enable: False 
  snr: 9 #dB
  padding_len: 20  

usrp:
  band: n78
  center_freq: 440 #MHxz
  sampling_rate: 196 #KSPS
